/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:8cd6076a-fed9-4b4b-99ca-2699d23b2429",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_jOKeylGEI",
    "aws_user_pools_web_client_id": "77n8u5ochlj3vmtdtapt0gkgdf",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ti4h2ctvlzdbtoidcevsqeomtu.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
